# Generated by Django 3.1.7 on 2021-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifications',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
